/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FacultyRouteImport } from './routes/faculty'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as StudentRouteImport } from './routes/student'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminComplaintsRouteImport } from './routes/admin.complaints'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminFacultyRouteImport } from './routes/admin.faculty'
import { Route as AdminLostFoundRouteImport } from './routes/admin.lost-found'
import { Route as AdminNoticesRouteImport } from './routes/admin.notices'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as FacultyIndexRouteImport } from './routes/faculty.index'
import { Route as FacultyAssignmentsRouteImport } from './routes/faculty.assignments'
import { Route as FacultyAttendanceRouteImport } from './routes/faculty.attendance'
import { Route as FacultyClassesRouteImport } from './routes/faculty.classes'
import { Route as FacultyEventsRouteImport } from './routes/faculty.events'
import { Route as FacultyIssuesRouteImport } from './routes/faculty.issues'
import { Route as FacultyNoticesRouteImport } from './routes/faculty.notices'
import { Route as FacultyNotificationsRouteImport } from './routes/faculty.notifications'
import { Route as FacultyProfileRouteImport } from './routes/faculty.profile'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as StudentAssignmentsRouteImport } from './routes/student.assignments'
import { Route as StudentAssistantRouteImport } from './routes/student.assistant'
import { Route as StudentAttendanceRouteImport } from './routes/student.attendance'
import { Route as StudentComplaintsRouteImport } from './routes/student.complaints'
import { Route as StudentEventsRouteImport } from './routes/student.events'
import { Route as StudentLostFoundRouteImport } from './routes/student.lost-found'
import { Route as StudentNoticesRouteImport } from './routes/student.notices'
import { Route as StudentNotificationsRouteImport } from './routes/student.notifications'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentTimetableRouteImport } from './routes/student.timetable'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyRoute = FacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComplaintsRoute = AdminComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFacultyRoute = AdminFacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLostFoundRoute = AdminLostFoundRouteImport.update({
  id: '/lost-found',
  path: '/lost-found',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNoticesRoute = AdminNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const FacultyIndexRoute = FacultyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FacultyRoute,
} as any)
const FacultyAssignmentsRoute = FacultyAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => FacultyRoute,
} as any)
const FacultyAttendanceRoute = FacultyAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => FacultyRoute,
} as any)
const FacultyClassesRoute = FacultyClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => FacultyRoute,
} as any)
const FacultyEventsRoute = FacultyEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => FacultyRoute,
} as any)
const FacultyIssuesRoute = FacultyIssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => FacultyRoute,
} as any)
const FacultyNoticesRoute = FacultyNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => FacultyRoute,
} as any)
const FacultyNotificationsRoute = FacultyNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => FacultyRoute,
} as any)
const FacultyProfileRoute = FacultyProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => FacultyRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAssignmentsRoute = StudentAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAssistantRoute = StudentAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAttendanceRoute = StudentAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => StudentRoute,
} as any)
const StudentComplaintsRoute = StudentComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => StudentRoute,
} as any)
const StudentEventsRoute = StudentEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => StudentRoute,
} as any)
const StudentLostFoundRoute = StudentLostFoundRouteImport.update({
  id: '/lost-found',
  path: '/lost-found',
  getParentRoute: () => StudentRoute,
} as any)
const StudentNoticesRoute = StudentNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => StudentRoute,
} as any)
const StudentNotificationsRoute = StudentNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentTimetableRoute = StudentTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => StudentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/faculty': typeof FacultyRouteWithChildren
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/student': typeof StudentRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/complaints': typeof AdminComplaintsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/faculty': typeof AdminFacultyRoute
  '/admin/lost-found': typeof AdminLostFoundRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/faculty/assignments': typeof FacultyAssignmentsRoute
  '/faculty/attendance': typeof FacultyAttendanceRoute
  '/faculty/classes': typeof FacultyClassesRoute
  '/faculty/events': typeof FacultyEventsRoute
  '/faculty/issues': typeof FacultyIssuesRoute
  '/faculty/notices': typeof FacultyNoticesRoute
  '/faculty/notifications': typeof FacultyNotificationsRoute
  '/faculty/profile': typeof FacultyProfileRoute
  '/student/assignments': typeof StudentAssignmentsRoute
  '/student/assistant': typeof StudentAssistantRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/complaints': typeof StudentComplaintsRoute
  '/student/events': typeof StudentEventsRoute
  '/student/lost-found': typeof StudentLostFoundRoute
  '/student/notices': typeof StudentNoticesRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/timetable': typeof StudentTimetableRoute
  '/admin/': typeof AdminIndexRoute
  '/faculty/': typeof FacultyIndexRoute
  '/student/': typeof StudentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/complaints': typeof AdminComplaintsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/faculty': typeof AdminFacultyRoute
  '/admin/lost-found': typeof AdminLostFoundRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/faculty/assignments': typeof FacultyAssignmentsRoute
  '/faculty/attendance': typeof FacultyAttendanceRoute
  '/faculty/classes': typeof FacultyClassesRoute
  '/faculty/events': typeof FacultyEventsRoute
  '/faculty/issues': typeof FacultyIssuesRoute
  '/faculty/notices': typeof FacultyNoticesRoute
  '/faculty/notifications': typeof FacultyNotificationsRoute
  '/faculty/profile': typeof FacultyProfileRoute
  '/student/assignments': typeof StudentAssignmentsRoute
  '/student/assistant': typeof StudentAssistantRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/complaints': typeof StudentComplaintsRoute
  '/student/events': typeof StudentEventsRoute
  '/student/lost-found': typeof StudentLostFoundRoute
  '/student/notices': typeof StudentNoticesRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/timetable': typeof StudentTimetableRoute
  '/admin': typeof AdminIndexRoute
  '/faculty': typeof FacultyIndexRoute
  '/student': typeof StudentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/faculty': typeof FacultyRouteWithChildren
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/student': typeof StudentRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/complaints': typeof AdminComplaintsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/faculty': typeof AdminFacultyRoute
  '/admin/lost-found': typeof AdminLostFoundRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/faculty/assignments': typeof FacultyAssignmentsRoute
  '/faculty/attendance': typeof FacultyAttendanceRoute
  '/faculty/classes': typeof FacultyClassesRoute
  '/faculty/events': typeof FacultyEventsRoute
  '/faculty/issues': typeof FacultyIssuesRoute
  '/faculty/notices': typeof FacultyNoticesRoute
  '/faculty/notifications': typeof FacultyNotificationsRoute
  '/faculty/profile': typeof FacultyProfileRoute
  '/student/assignments': typeof StudentAssignmentsRoute
  '/student/assistant': typeof StudentAssistantRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/complaints': typeof StudentComplaintsRoute
  '/student/events': typeof StudentEventsRoute
  '/student/lost-found': typeof StudentLostFoundRoute
  '/student/notices': typeof StudentNoticesRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/timetable': typeof StudentTimetableRoute
  '/admin/': typeof AdminIndexRoute
  '/faculty/': typeof FacultyIndexRoute
  '/student/': typeof StudentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/faculty'
    | '/features'
    | '/login'
    | '/register'
    | '/student'
    | '/admin/analytics'
    | '/admin/complaints'
    | '/admin/events'
    | '/admin/faculty'
    | '/admin/lost-found'
    | '/admin/notices'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/students'
    | '/faculty/assignments'
    | '/faculty/attendance'
    | '/faculty/classes'
    | '/faculty/events'
    | '/faculty/issues'
    | '/faculty/notices'
    | '/faculty/notifications'
    | '/faculty/profile'
    | '/student/assignments'
    | '/student/assistant'
    | '/student/attendance'
    | '/student/complaints'
    | '/student/events'
    | '/student/lost-found'
    | '/student/notices'
    | '/student/notifications'
    | '/student/profile'
    | '/student/timetable'
    | '/admin/'
    | '/faculty/'
    | '/student/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/features'
    | '/login'
    | '/register'
    | '/admin/analytics'
    | '/admin/complaints'
    | '/admin/events'
    | '/admin/faculty'
    | '/admin/lost-found'
    | '/admin/notices'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/students'
    | '/faculty/assignments'
    | '/faculty/attendance'
    | '/faculty/classes'
    | '/faculty/events'
    | '/faculty/issues'
    | '/faculty/notices'
    | '/faculty/notifications'
    | '/faculty/profile'
    | '/student/assignments'
    | '/student/assistant'
    | '/student/attendance'
    | '/student/complaints'
    | '/student/events'
    | '/student/lost-found'
    | '/student/notices'
    | '/student/notifications'
    | '/student/profile'
    | '/student/timetable'
    | '/admin'
    | '/faculty'
    | '/student'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/faculty'
    | '/features'
    | '/login'
    | '/register'
    | '/student'
    | '/admin/analytics'
    | '/admin/complaints'
    | '/admin/events'
    | '/admin/faculty'
    | '/admin/lost-found'
    | '/admin/notices'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/students'
    | '/faculty/assignments'
    | '/faculty/attendance'
    | '/faculty/classes'
    | '/faculty/events'
    | '/faculty/issues'
    | '/faculty/notices'
    | '/faculty/notifications'
    | '/faculty/profile'
    | '/student/assignments'
    | '/student/assistant'
    | '/student/attendance'
    | '/student/complaints'
    | '/student/events'
    | '/student/lost-found'
    | '/student/notices'
    | '/student/notifications'
    | '/student/profile'
    | '/student/timetable'
    | '/admin/'
    | '/faculty/'
    | '/student/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  FacultyRoute: typeof FacultyRouteWithChildren
  FeaturesRoute: typeof FeaturesRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  StudentRoute: typeof StudentRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty': {
      id: '/faculty'
      path: '/faculty'
      fullPath: '/faculty'
      preLoaderRoute: typeof FacultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/complaints': {
      id: '/admin/complaints'
      path: '/complaints'
      fullPath: '/admin/complaints'
      preLoaderRoute: typeof AdminComplaintsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faculty': {
      id: '/admin/faculty'
      path: '/faculty'
      fullPath: '/admin/faculty'
      preLoaderRoute: typeof AdminFacultyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lost-found': {
      id: '/admin/lost-found'
      path: '/lost-found'
      fullPath: '/admin/lost-found'
      preLoaderRoute: typeof AdminLostFoundRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notices': {
      id: '/admin/notices'
      path: '/notices'
      fullPath: '/admin/notices'
      preLoaderRoute: typeof AdminNoticesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/faculty/': {
      id: '/faculty/'
      path: '/'
      fullPath: '/faculty/'
      preLoaderRoute: typeof FacultyIndexRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/faculty/assignments': {
      id: '/faculty/assignments'
      path: '/assignments'
      fullPath: '/faculty/assignments'
      preLoaderRoute: typeof FacultyAssignmentsRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/faculty/attendance': {
      id: '/faculty/attendance'
      path: '/attendance'
      fullPath: '/faculty/attendance'
      preLoaderRoute: typeof FacultyAttendanceRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/faculty/classes': {
      id: '/faculty/classes'
      path: '/classes'
      fullPath: '/faculty/classes'
      preLoaderRoute: typeof FacultyClassesRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/faculty/events': {
      id: '/faculty/events'
      path: '/events'
      fullPath: '/faculty/events'
      preLoaderRoute: typeof FacultyEventsRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/faculty/issues': {
      id: '/faculty/issues'
      path: '/issues'
      fullPath: '/faculty/issues'
      preLoaderRoute: typeof FacultyIssuesRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/faculty/notices': {
      id: '/faculty/notices'
      path: '/notices'
      fullPath: '/faculty/notices'
      preLoaderRoute: typeof FacultyNoticesRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/faculty/notifications': {
      id: '/faculty/notifications'
      path: '/notifications'
      fullPath: '/faculty/notifications'
      preLoaderRoute: typeof FacultyNotificationsRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/faculty/profile': {
      id: '/faculty/profile'
      path: '/profile'
      fullPath: '/faculty/profile'
      preLoaderRoute: typeof FacultyProfileRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/assignments': {
      id: '/student/assignments'
      path: '/assignments'
      fullPath: '/student/assignments'
      preLoaderRoute: typeof StudentAssignmentsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/assistant': {
      id: '/student/assistant'
      path: '/assistant'
      fullPath: '/student/assistant'
      preLoaderRoute: typeof StudentAssistantRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/attendance': {
      id: '/student/attendance'
      path: '/attendance'
      fullPath: '/student/attendance'
      preLoaderRoute: typeof StudentAttendanceRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/complaints': {
      id: '/student/complaints'
      path: '/complaints'
      fullPath: '/student/complaints'
      preLoaderRoute: typeof StudentComplaintsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/events': {
      id: '/student/events'
      path: '/events'
      fullPath: '/student/events'
      preLoaderRoute: typeof StudentEventsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/lost-found': {
      id: '/student/lost-found'
      path: '/lost-found'
      fullPath: '/student/lost-found'
      preLoaderRoute: typeof StudentLostFoundRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/notices': {
      id: '/student/notices'
      path: '/notices'
      fullPath: '/student/notices'
      preLoaderRoute: typeof StudentNoticesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/notifications': {
      id: '/student/notifications'
      path: '/notifications'
      fullPath: '/student/notifications'
      preLoaderRoute: typeof StudentNotificationsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/timetable': {
      id: '/student/timetable'
      path: '/timetable'
      fullPath: '/student/timetable'
      preLoaderRoute: typeof StudentTimetableRouteImport
      parentRoute: typeof StudentRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminComplaintsRoute: typeof AdminComplaintsRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminFacultyRoute: typeof AdminFacultyRoute
  AdminLostFoundRoute: typeof AdminLostFoundRoute
  AdminNoticesRoute: typeof AdminNoticesRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminComplaintsRoute: AdminComplaintsRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminFacultyRoute: AdminFacultyRoute,
  AdminLostFoundRoute: AdminLostFoundRoute,
  AdminNoticesRoute: AdminNoticesRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface FacultyRouteChildren {
  FacultyAssignmentsRoute: typeof FacultyAssignmentsRoute
  FacultyAttendanceRoute: typeof FacultyAttendanceRoute
  FacultyClassesRoute: typeof FacultyClassesRoute
  FacultyEventsRoute: typeof FacultyEventsRoute
  FacultyIssuesRoute: typeof FacultyIssuesRoute
  FacultyNoticesRoute: typeof FacultyNoticesRoute
  FacultyNotificationsRoute: typeof FacultyNotificationsRoute
  FacultyProfileRoute: typeof FacultyProfileRoute
  FacultyIndexRoute: typeof FacultyIndexRoute
}

const FacultyRouteChildren: FacultyRouteChildren = {
  FacultyAssignmentsRoute: FacultyAssignmentsRoute,
  FacultyAttendanceRoute: FacultyAttendanceRoute,
  FacultyClassesRoute: FacultyClassesRoute,
  FacultyEventsRoute: FacultyEventsRoute,
  FacultyIssuesRoute: FacultyIssuesRoute,
  FacultyNoticesRoute: FacultyNoticesRoute,
  FacultyNotificationsRoute: FacultyNotificationsRoute,
  FacultyProfileRoute: FacultyProfileRoute,
  FacultyIndexRoute: FacultyIndexRoute,
}

const FacultyRouteWithChildren =
  FacultyRoute._addFileChildren(FacultyRouteChildren)

interface StudentRouteChildren {
  StudentAssignmentsRoute: typeof StudentAssignmentsRoute
  StudentAssistantRoute: typeof StudentAssistantRoute
  StudentAttendanceRoute: typeof StudentAttendanceRoute
  StudentComplaintsRoute: typeof StudentComplaintsRoute
  StudentEventsRoute: typeof StudentEventsRoute
  StudentLostFoundRoute: typeof StudentLostFoundRoute
  StudentNoticesRoute: typeof StudentNoticesRoute
  StudentNotificationsRoute: typeof StudentNotificationsRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentTimetableRoute: typeof StudentTimetableRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentAssignmentsRoute: StudentAssignmentsRoute,
  StudentAssistantRoute: StudentAssistantRoute,
  StudentAttendanceRoute: StudentAttendanceRoute,
  StudentComplaintsRoute: StudentComplaintsRoute,
  StudentEventsRoute: StudentEventsRoute,
  StudentLostFoundRoute: StudentLostFoundRoute,
  StudentNoticesRoute: StudentNoticesRoute,
  StudentNotificationsRoute: StudentNotificationsRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentTimetableRoute: StudentTimetableRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  FacultyRoute: FacultyRouteWithChildren,
  FeaturesRoute: FeaturesRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  StudentRoute: StudentRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
