/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as FacultyRouteImport } from './routes/faculty'
import { Route as StudentRouteImport } from './routes/student'
import { Route as AdminComplaintsRouteImport } from './routes/admin.complaints'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminLostFoundRouteImport } from './routes/admin.lost-found'
import { Route as AdminNoticesRouteImport } from './routes/admin.notices'
import { Route as FacultyIssuesRouteImport } from './routes/faculty.issues'
import { Route as FacultyNoticesRouteImport } from './routes/faculty.notices'
import { Route as FacultyProfileRouteImport } from './routes/faculty.profile'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as StudentAssignmentsRouteImport } from './routes/student.assignments'
import { Route as StudentAssistantRouteImport } from './routes/student.assistant'
import { Route as StudentAttendanceRouteImport } from './routes/student.attendance'
import { Route as StudentComplaintsRouteImport } from './routes/student.complaints'
import { Route as StudentEventsRouteImport } from './routes/student.events'
import { Route as StudentLostFoundRouteImport } from './routes/student.lost-found'
import { Route as StudentNoticesRouteImport } from './routes/student.notices'
import { Route as StudentNotificationsRouteImport } from './routes/student.notifications'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentTimetableRouteImport } from './routes/student.timetable'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyRoute = FacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminComplaintsRoute = AdminComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLostFoundRoute = AdminLostFoundRouteImport.update({
  id: '/lost-found',
  path: '/lost-found',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNoticesRoute = AdminNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => AdminRoute,
} as any)
const FacultyIssuesRoute = FacultyIssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => FacultyRoute,
} as any)
const FacultyNoticesRoute = FacultyNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => FacultyRoute,
} as any)
const FacultyProfileRoute = FacultyProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => FacultyRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAssignmentsRoute = StudentAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAssistantRoute = StudentAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAttendanceRoute = StudentAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => StudentRoute,
} as any)
const StudentComplaintsRoute = StudentComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => StudentRoute,
} as any)
const StudentEventsRoute = StudentEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => StudentRoute,
} as any)
const StudentLostFoundRoute = StudentLostFoundRouteImport.update({
  id: '/lost-found',
  path: '/lost-found',
  getParentRoute: () => StudentRoute,
} as any)
const StudentNoticesRoute = StudentNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => StudentRoute,
} as any)
const StudentNotificationsRoute = StudentNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentTimetableRoute = StudentTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => StudentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/faculty': typeof FacultyRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/admin/complaints': typeof AdminComplaintsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/lost-found': typeof AdminLostFoundRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/faculty/issues': typeof FacultyIssuesRoute
  '/faculty/notices': typeof FacultyNoticesRoute
  '/faculty/profile': typeof FacultyProfileRoute
  '/student/assignments': typeof StudentAssignmentsRoute
  '/student/assistant': typeof StudentAssistantRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/complaints': typeof StudentComplaintsRoute
  '/student/events': typeof StudentEventsRoute
  '/student/lost-found': typeof StudentLostFoundRoute
  '/student/notices': typeof StudentNoticesRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/timetable': typeof StudentTimetableRoute
  '/student/': typeof StudentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/faculty': typeof FacultyRouteWithChildren
  '/admin/complaints': typeof AdminComplaintsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/lost-found': typeof AdminLostFoundRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/faculty/issues': typeof FacultyIssuesRoute
  '/faculty/notices': typeof FacultyNoticesRoute
  '/faculty/profile': typeof FacultyProfileRoute
  '/student/assignments': typeof StudentAssignmentsRoute
  '/student/assistant': typeof StudentAssistantRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/complaints': typeof StudentComplaintsRoute
  '/student/events': typeof StudentEventsRoute
  '/student/lost-found': typeof StudentLostFoundRoute
  '/student/notices': typeof StudentNoticesRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/timetable': typeof StudentTimetableRoute
  '/student': typeof StudentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/faculty': typeof FacultyRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/admin/complaints': typeof AdminComplaintsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/lost-found': typeof AdminLostFoundRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/faculty/issues': typeof FacultyIssuesRoute
  '/faculty/notices': typeof FacultyNoticesRoute
  '/faculty/profile': typeof FacultyProfileRoute
  '/student/assignments': typeof StudentAssignmentsRoute
  '/student/assistant': typeof StudentAssistantRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/complaints': typeof StudentComplaintsRoute
  '/student/events': typeof StudentEventsRoute
  '/student/lost-found': typeof StudentLostFoundRoute
  '/student/notices': typeof StudentNoticesRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/timetable': typeof StudentTimetableRoute
  '/student/': typeof StudentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/faculty'
    | '/student'
    | '/admin/complaints'
    | '/admin/events'
    | '/admin/lost-found'
    | '/admin/notices'
    | '/faculty/issues'
    | '/faculty/notices'
    | '/faculty/profile'
    | '/student/assignments'
    | '/student/assistant'
    | '/student/attendance'
    | '/student/complaints'
    | '/student/events'
    | '/student/lost-found'
    | '/student/notices'
    | '/student/notifications'
    | '/student/profile'
    | '/student/timetable'
    | '/student/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/faculty'
    | '/admin/complaints'
    | '/admin/events'
    | '/admin/lost-found'
    | '/admin/notices'
    | '/faculty/issues'
    | '/faculty/notices'
    | '/faculty/profile'
    | '/student/assignments'
    | '/student/assistant'
    | '/student/attendance'
    | '/student/complaints'
    | '/student/events'
    | '/student/lost-found'
    | '/student/notices'
    | '/student/notifications'
    | '/student/profile'
    | '/student/timetable'
    | '/student'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/faculty'
    | '/student'
    | '/admin/complaints'
    | '/admin/events'
    | '/admin/lost-found'
    | '/admin/notices'
    | '/faculty/issues'
    | '/faculty/notices'
    | '/faculty/profile'
    | '/student/assignments'
    | '/student/assistant'
    | '/student/attendance'
    | '/student/complaints'
    | '/student/events'
    | '/student/lost-found'
    | '/student/notices'
    | '/student/notifications'
    | '/student/profile'
    | '/student/timetable'
    | '/student/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  FacultyRoute: typeof FacultyRouteWithChildren
  StudentRoute: typeof StudentRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty': {
      id: '/faculty'
      path: '/faculty'
      fullPath: '/faculty'
      preLoaderRoute: typeof FacultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/complaints': {
      id: '/admin/complaints'
      path: '/complaints'
      fullPath: '/admin/complaints'
      preLoaderRoute: typeof AdminComplaintsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lost-found': {
      id: '/admin/lost-found'
      path: '/lost-found'
      fullPath: '/admin/lost-found'
      preLoaderRoute: typeof AdminLostFoundRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notices': {
      id: '/admin/notices'
      path: '/notices'
      fullPath: '/admin/notices'
      preLoaderRoute: typeof AdminNoticesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/faculty/issues': {
      id: '/faculty/issues'
      path: '/issues'
      fullPath: '/faculty/issues'
      preLoaderRoute: typeof FacultyIssuesRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/faculty/notices': {
      id: '/faculty/notices'
      path: '/notices'
      fullPath: '/faculty/notices'
      preLoaderRoute: typeof FacultyNoticesRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/faculty/profile': {
      id: '/faculty/profile'
      path: '/profile'
      fullPath: '/faculty/profile'
      preLoaderRoute: typeof FacultyProfileRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/assignments': {
      id: '/student/assignments'
      path: '/assignments'
      fullPath: '/student/assignments'
      preLoaderRoute: typeof StudentAssignmentsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/assistant': {
      id: '/student/assistant'
      path: '/assistant'
      fullPath: '/student/assistant'
      preLoaderRoute: typeof StudentAssistantRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/attendance': {
      id: '/student/attendance'
      path: '/attendance'
      fullPath: '/student/attendance'
      preLoaderRoute: typeof StudentAttendanceRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/complaints': {
      id: '/student/complaints'
      path: '/complaints'
      fullPath: '/student/complaints'
      preLoaderRoute: typeof StudentComplaintsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/events': {
      id: '/student/events'
      path: '/events'
      fullPath: '/student/events'
      preLoaderRoute: typeof StudentEventsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/lost-found': {
      id: '/student/lost-found'
      path: '/lost-found'
      fullPath: '/student/lost-found'
      preLoaderRoute: typeof StudentLostFoundRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/notices': {
      id: '/student/notices'
      path: '/notices'
      fullPath: '/student/notices'
      preLoaderRoute: typeof StudentNoticesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/notifications': {
      id: '/student/notifications'
      path: '/notifications'
      fullPath: '/student/notifications'
      preLoaderRoute: typeof StudentNotificationsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/timetable': {
      id: '/student/timetable'
      path: '/timetable'
      fullPath: '/student/timetable'
      preLoaderRoute: typeof StudentTimetableRouteImport
      parentRoute: typeof StudentRoute
    }
  }
}

interface AdminRouteChildren {
  AdminComplaintsRoute: typeof AdminComplaintsRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminLostFoundRoute: typeof AdminLostFoundRoute
  AdminNoticesRoute: typeof AdminNoticesRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminComplaintsRoute: AdminComplaintsRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminLostFoundRoute: AdminLostFoundRoute,
  AdminNoticesRoute: AdminNoticesRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface FacultyRouteChildren {
  FacultyIssuesRoute: typeof FacultyIssuesRoute
  FacultyNoticesRoute: typeof FacultyNoticesRoute
  FacultyProfileRoute: typeof FacultyProfileRoute
}

const FacultyRouteChildren: FacultyRouteChildren = {
  FacultyIssuesRoute: FacultyIssuesRoute,
  FacultyNoticesRoute: FacultyNoticesRoute,
  FacultyProfileRoute: FacultyProfileRoute,
}

const FacultyRouteWithChildren =
  FacultyRoute._addFileChildren(FacultyRouteChildren)

interface StudentRouteChildren {
  StudentAssignmentsRoute: typeof StudentAssignmentsRoute
  StudentAssistantRoute: typeof StudentAssistantRoute
  StudentAttendanceRoute: typeof StudentAttendanceRoute
  StudentComplaintsRoute: typeof StudentComplaintsRoute
  StudentEventsRoute: typeof StudentEventsRoute
  StudentLostFoundRoute: typeof StudentLostFoundRoute
  StudentNoticesRoute: typeof StudentNoticesRoute
  StudentNotificationsRoute: typeof StudentNotificationsRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentTimetableRoute: typeof StudentTimetableRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentAssignmentsRoute: StudentAssignmentsRoute,
  StudentAssistantRoute: StudentAssistantRoute,
  StudentAttendanceRoute: StudentAttendanceRoute,
  StudentComplaintsRoute: StudentComplaintsRoute,
  StudentEventsRoute: StudentEventsRoute,
  StudentLostFoundRoute: StudentLostFoundRoute,
  StudentNoticesRoute: StudentNoticesRoute,
  StudentNotificationsRoute: StudentNotificationsRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentTimetableRoute: StudentTimetableRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  FacultyRoute: FacultyRouteWithChildren,
  StudentRoute: StudentRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
